export const domain = 'https://barbers-dev.space'

export const AUTH = '/auth/send'
export const LOGIN = '/auth/confirm'
export const PROFILE = '/user/me'
export const BARBERS_LIST = '/barber/filter'
export const BARBERS_UPDATE = '/barber/my/edit'
export const BARBER_CREATE = '/barber/create'
export const BARBER_ACTIVATE = 'barber/{id}/activate'
export const BARBER_EDIT = 'barber/{id}/edit'
export const BARBER_DELETE = 'barber/{id}/delete'
export const SERVICES_LIST = '/service/get'
export const SERVICES_CREATE = '/service/create'
export const SERVICE_EDIT = '/service/{id}/edit'
export const SERVICE_DELETE = '/service/{id}/delete'
